server:
  port: 80

spring:
  application:
    name: mhp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: mhp-account
          uri: lb://mhp-account
          predicates:
            - Path=/api/user/**, /api/merchant/**

        - id: mhp-booking
          uri: lb://mhp-booking
          predicates:
            - Path=/api/schedule/**, /api/booking/**, /api/questionnaire/**

        - id: mhp-social
          uri: lb://mhp-social
          predicates:
            - Path=/api/post/**, /api/follow/**, /api/review/**, /api/complaint/**, /api/message/**, /api/upload/**, /ws/**
